### ISSUE TITLE
Summary list passthrough

### ISSUE THREAD

**Issue by natlibfi-jonollil** [mikaelvesavuori/license-compliance-action#1]
When action is successfully passed is it possible to log summary list of licenses like shown in [example](https://github.com/tmorell/license-compliance#examples)?

**Comment by mikaelvesavuori** [comment]
I've now added support for this in `1.0.1`. Note that the default behavior is _no output_ if all licenses are OK. I've now added the overall summary before doing the actual check.

Will close as a result. Please re-open if needed.

https://github.com/mikaelvesavuori/license-compliance-action/releases/tag/v1.0.1
